### ISSUE TITLE
[BUGFIX] Make CornerButtons call OnPress When Anywhere On Button Pressed

### ISSUE THREAD

**Issue by R303Vermeulen** [apandey16/Meat_and_Feat#14]
Currently, CornerButtons can only call the OnPress function when the text is pressed. Should be called whenever anywhere within button is pressed

**Comment by MorrowCameron** [comment]
Is this fixed or still happening?

**Comment by R303Vermeulen** [comment]
Still happening. I tried a couple quick fixes which didn't work.

**Comment by MorrowCameron** [comment]
Did some research and am looking into using a touchableHighlight in the background. I can take this ticket

**Comment by MorrowCameron** [comment]
Fixed Rounded button if that's the one this is talking about, can fix cornered button too.

**Comment by MorrowCameron** [comment]
This is done, reopen if it reappears
