### ISSUE TITLE
[FUNC] Optimize Toolbar.tsx

### ISSUE THREAD

**Issue by R303Vermeulen** [apandey16/Meat_and_Feat#35]
consider putting the paths in two arrays or hashmaps (blackImagePaths & whiteImagePaths) based on their color, for ordering.

**Comment by MorrowCameron** [comment]
Here's the issue with require with props/non literal strings: https://stackoverflow.com/questions/48385073/pass-the-local-image-path-as-a-prop-between-two-functional-components. Just a jumping off point.

**Comment by MorrowCameron** [comment]
I believe rob fixed this
