### ISSUE TITLE
[UI] Create NavBar

### ISSUE THREAD

**Issue by MorrowCameron** [apandey16/Meat_and_Feat#6]
Create the Nav Bar to put at the top of screens. Should not be on the log in page or onboarding, but most others.

**Comment by MorrowCameron** [comment]
Make this a component with 6 clickable icons, visible on the figma

**Comment by apandey16** [comment]
made the six icons and they appear to be clickable, need to add page changes and move to top of screen but UI looks to be in place

**Comment by apandey16** [comment]
Made and committed as a branch, need to merge
